from .user.login import LoginForm
from .user.registration import RegistrationForm
from .event.createevent import EventForm
from .event.editvenue import EditVenueForm
from .tickets.addtickets import AddTicketForm
from .tickets.payment import PaymentMethodForm
from .tickets.ticketquantity import ChooseQuantityForm
from .user.editpassword import EditPasswordForm
from .user.edituseremail import EditEmailForm
from .user.edittags import EditTagsForm